version: "3"

services:
  kanban-postgres:
    image: postgres
    container_name: kanban-postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - kanban-postgres-data:/data
    networks:
      - kanban-network

  kanban-api:
    build: .
    container_name: kanban-api
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    command: bash -c "yarn typeorm migration:run && yarn start"
    ports:
      - "${API_PORT}:3333"
    networks:
      - kanban-network
    depends_on:
      - kanban-postgres

volumes:
  kanban-postgres-data:

networks:
  kanban-network:
    driver: bridge
